import { Fahkwang, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const fahkwangFont = Fahkwang({
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700']
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${fahkwangFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* <Navbar></Navbar> */}
        <main>
          {children}
        </main>
        {/* <Footer></Footer> */}
      </body>
    </html>
  );
}
